/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ims;

import java.awt.print.PrinterException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ADARSH
 */
public class Bill extends javax.swing.JFrame {

    /**
     * Creates new form Bill
     */
    public Bill() {
        initComponents();
    }
    
    String ltotal;
    String lpay;
    String lbalance;
    
    
    public Bill(String total,String pay,String balance,TableModel tableModel) throws PrinterException {
        initComponents();
        
        this.ltotal = total;
        this.lpay = pay;
        this.lbalance = balance;
        
        
        bill_txt.setText(bill_txt.getText() + "********************************************\n");
        bill_txt.setText(bill_txt.getText() + "                     Bill\n");
        bill_txt.setText(bill_txt.getText() + "********************************************\n");
        bill_txt.setText(bill_txt.getText() + "Product"+"\t\t"+"Qty" + "\t"+"Rate" + "\t"+"Amount");
        bill_txt.setText(bill_txt.getText() + "\n");
        bill_txt.setText(bill_txt.getText() + "\n");
        
        for(int i = 0; i < tableModel.getRowCount(); i++)
        {
            String product = (String) tableModel.getValueAt(i, 0);
            String quantity = (String) tableModel.getValueAt(i, 2);
            String price = (String) tableModel.getValueAt(i, 1);
            int amount = (int) tableModel.getValueAt(i, 3);
            
            bill_txt.setText(bill_txt.getText() + product+"\t\t"+quantity + "\t"+price + "\t"+amount+"\n");
        }
        bill_txt.setText(bill_txt.getText() + "\n");
        bill_txt.setText(bill_txt.getText() + "\n");
        
        bill_txt.setText(bill_txt.getText() + "                        " + "Total : " + total +     "\n");
        bill_txt.setText(bill_txt.getText() + "                        " + "Pay : " + pay +     "\n");
        bill_txt.setText(bill_txt.getText() + "                        " + "Balance : " + balance +     "\n");
        
         bill_txt.setText(bill_txt.getText() + "********************************************\n");
         bill_txt.setText(bill_txt.getText() + "           Thank you come again...\n");
         bill_txt.setText(bill_txt.getText() + "********************************************\n");
        
        bill_txt.print();
    }

    

    /*public void bill()
    {
        DefaultTableModel d = new DefaultTableModel();
      
        
        bill_txt.setText(bill_txt.getText() + "**********************************************\n");
        bill_txt.setText(bill_txt.getText() + "                     Bill\n");
        bill_txt.setText(bill_txt.getText() + "**********************************************\n");
        
        bill_txt.setText(bill_txt.getText() + "Product              Qty      Rate      Amount\n");
        
        
    }
    */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bill_txt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(422, 523));
        setResizable(false);

        bill_txt.setColumns(20);
        bill_txt.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        bill_txt.setRows(5);
        jScrollPane1.setViewportView(bill_txt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bill_txt;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
